development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://zglzuaauroqvce:BaCH0EGYGJ-6ck00nK9DVQOBFn@ec2-54-221-244-190.compute-1.amazonaws.com:5432/d8roud0fbf8meg
